### ISSUE TITLE
the links not working

### ISSUE THREAD

**Issue by tokiijnr** [JoulioK/Phishing_Kits#1]
iforgot.support.account.service.integrityappid.com
![Screenshot from 2019-06-25 13-51-36](https://user-images.githubusercontent.com/49600154/60099843-676ec000-9750-11e9-8dc0-bfcfa387e74c.png)

**Comment by JoulioK** [comment]
It does work if not browsing your localhost, make sure you get it from (https://github.com/JoulioK/Phishing_Kits/blob/master/iforgot.support.account.service.integrityappid.com/SCP.zip)

![SCP](https://user-images.githubusercontent.com/17366067/60101839-63dd3800-9754-11e9-9d28-c9ea42977238.PNG)

**Comment by tokiijnr** [comment]
hey see this

**Comment by tokiijnr** [comment]
links not working
