### ISSUE TITLE
Cooperation to remove sensitive information

### ISSUE THREAD

**Issue by CsirtEntelgy** [JoulioK/Phishing_Kits#4]
Dear Developer,

We are contacting you regarding a repository you have hosted on Github that contains information related to Banco Santander.

We do not want to cause you any problem with this platform or your code but, we would appreciate if you could collaborate with us and remove a part of the code where Santander is mentioned.

Specifically, in your repository:
https://github.com/Wh014M/Phishing_Kits-1/tree/master/bancosantander.es.particulares.freestormbringer.com

The file:
drbtc.zip

After analyzing the file, we have been able to verify that it is a kit to perform phishing attacks against Santander.

We would be grateful if you would remove the content as this information owned by certain people could pose a security risk of users.

We thank you in advance for your cooperation and insist that we do not want to harm your work and collaboration on the platform.

Best regards.

**Comment by JoulioK** [comment]
Hi,

Thanks for your email.

I can confirm that the file mentioned has been deleted, and hosting such
files are solely for the purpose of hunting bad actors and identifying
phishing campaigns.

Please do let me know if you require any further information.

Kind regards,
Joul Kouchakji

**Comment by CsirtEntelgy** [comment]
Dear team.

We are contacting you to ask you to check the repository again as it seems
to be still active.

We are very grateful for your cooperation.

amenazas cibernéticas

***@***.***

T. +34 911 453 630



La información incluida en el presente correo electrónico es
confidencial, siendo para uso exclusivo del destinatario arriba mencionado.
Si Vd. lee este mensaje y no es el receptor señalado, el empleado o el
agente responsable de entregar el mensaje al destinatario, o ha recibido
esta comunicación por error, le informamos que está totalmente prohibida
cualquier divulgación, distribución o reproducción, y le rogamos que nos
lo notifique, nos devuelva el mensaje original a la dirección arriba
mencionada y lo borre. Gracias
